const JARGON_DICT = {
  "rest happy": "REST API",
  "koo bernetties": "Kubernetes",
  "dock her": "Docker",
  "jee san": "JSON",
  "ess queue ell": "SQL",
  "ess cue el": "SQL",
  "my ess cue ell": "MySQL",
  "post grass": "Postgres",
  "air pee": "RPA",
  "ai emm el": "HTML",
  "see es ess": "CSS",
  "gee dee pee": "GDP",
  "ro ai": "ROI",
  "key pee ai": "KPI",
  "s a es": "SaaS",
  "cr em": "CRM",
  "s er em": "CRM",
  "team siek": "TeamSync",
  "link din": "LinkedIn",
  "git hop": "GitHub",
  "lead gen": "lead generation",
  "top off funnel": "top of funnel",
  "bot off funnel": "bottom of funnel",
  "see ar er": "conversion rate",
  "quo ta": "quota",
  "pip line": "pipeline",
  "mo no repo": "monorepo",
  "micro ser vices": "microservices",
  "se ay": "CI/CD",
  "dee ev ops": "DevOps",
  "an jee ess": "AngularJS",
  "ree act": "React",
  "node jee ess": "Node.js",
  "spring boot": "Spring Boot",
  "arr arr": "annual recurring revenue",
  "yo why": "YOY",
  "ebee ta": "EBITDA",
  "cash flow": "cashflow",
  "gross marg in": "gross margin",
};

module.exports = JARGON_DICT;
